travis:
  secure:
    BINSTAR_TOKEN: jBYTqWW80Qral+HTIniHfcw4eqgo7fnlLe/wrxSMgHu2a38U/s2RfYqHAaJ97N08hsN1h9ujFsPcxvuBXRZ7WHu9hzy7BEkZU+9eoDAbc8TYDG7Dr0Gtr58NlD1FmhGNCRFTjzj4wMA0OWegr4DViqCtKzmYWoBwICbZVs0w72+51EYOq1rxlCagL98BdtHymzvHsHpKDU+uQSkgGS+R2tT1txnoxPmysW7I9b894RVXGYYxSRFxEsIGcjKNTAAr75esWwCM4n/j66k5I7UhHy096w8GM3IsqvHhlS+gk7GVaLCTuikbW2ETf2Xpfv392XqM9oe7AEu13Gsxr6wKuNWmJAonLvPp/A3ZLCdYxSGHCmRUbCEbC6mG0LLUZiv2Oc74BcDgGvRtS1N9zQ3o1r30rnxwCrXWA3Rsk8HmP8wd5hRfcqGVV2i3WaSVsubwJdfHHwTgcoD0mvcnsaJvPIVTPQn3/g/pvgr0YQJrNbZnAoLmxz22yHTKU5+6fY2e0c7MTRcOS38gODrwCa3Qi4+EMxFu3+uMJ+vPjoa0gftjbltklbKOvH1g37tCtMOG2ykNraqwCao7n+kMjcHQt9OQpjSe2EGPGDzV6y1oExzA2tav+IL9+7HB0qDtOwqk7v3zyYQUOVlnVbKkGBYsVGjxwc+NeK7u5ehJnpaErIY=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
